AllCops:
  Exclude:
    - db/schema.rb
    - bin/bundle
    - db/migrate/20220117203237_create_active_storage_tables.active_storage.rb

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false